spring:
  application-name: discount-order-app
discount:
  type: pct
  value: 5
  pct: 10
app:
  orders:
    - order-code: ABC123
      order-amount: 11.11
    - order-code: BCD234
      order-amount: 22.22
    - order-code: ZZZ123
      order-amount: 31.24